### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [Noahkiq/LoggerBot#1]
I need a way to get all text chat messages in all channels including PM's to ME. How can I do this? I don't want to make a discord bot, I want to login with my credentials and then save all messages to a log file on my hard drive.
Please, any info will be great. thx 🗡

**Comment by qixils** [comment]
The bot can't currently do this due to some issues I've encountered in Discord.Net 0.9.6, along with the fact that this would create tons of API events. Discord also doesn't support bots running on your own account.
