### ISSUE TITLE
Exception Unhandled Error

### ISSUE THREAD

**Issue by ghost** [Noahkiq/LoggerBot#2]
Discord.Net.WebSocketException: 'Received close code 4012: Requested gateway version is no longer supported or invalid'

**Comment by qixils** [comment]
sorry, this is no longer maintained. [try this](https://github.com/HTSTEM/DiscordBackup/blob/master/live.py), it should log messages to your terminal and to a sql database.

**Comment by ghost** [comment]
Okay, thanks
